# drawing
import turtle
turtle.setup(600, 600)
turtle.penup()
turtle.goto(-200, 200)
turtle.pendown()
turtle.pensize(3)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-200, -200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 200)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(100, 0)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(-100, -100)
turtle.pendown()
turtle.pensize(1)
for i in range(4):
    turtle.fd(400)
    turtle.right(90)
turtle.penup()
turtle.goto(0, -100)










